apiVersion: v2
name: clickstack
description: >-
  A Helm chart for ClickStack - Full-stack observability with ClickHouse,
  OpenTelemetry, and HyperDX
home: https://github.com/scottabeall/clickhouse-operator
sources:
  - https://github.com/scottabeall/clickhouse-operator
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/scottabeall/clickhouse-operator
    - name: Upstream Project
      url: https://github.com/scottabeall/clickhouse-operator
type: application
version: 2.1.1
appVersion: 2.24.1
dependencies:
  - name: opentelemetry-collector
    version: ~0.146.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    alias: otel-collector
    condition: otel-collector.enabled
